package com.crm.egift.services;

public enum ResultCodeEnum {
    OK("OK"),
    INVALID_CARD("01"),
    CUSTOMER_NOT_FOUND("02"),
    CUSTOMER_FINANCIAL_NOT_FOUND("03"),
    UNKNOWN_ERROR("99"),
    NOT_CONNECT_API("404"),
    REQUEST_TIMEOUT("408"),
    BAD_REQUEST("BAD_REQUEST"),
    MANY_REQUESTS("MANY_REQUESTS"),
    INVALIDLOGINEXCEPTION("INVALIDLOGINEXCEPTION"),
    READY_EXISTS_FOR_ANOTHER_CONTAC_TEXCEPTION("READY_EXISTS_FOR_ANOTHER_CONTAC_TEXCEPTION"),
    CANNOTSPENDAMOUNTWALLETBALANCENOTENOUGHEXCEPTION("CANNOTSPENDAMOUNTWALLETBALANCENOTENOUGHEXCEPTION"),
    NOTFOUNDEXCEPTION("NOTFOUNDEXCEPTION");

    private String label;
    ResultCodeEnum(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }
}
